### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by jevgenyonegin** [eda-abec/OneShot-GPS-Merge#1]
Hi.
Didn't get it working because of syntax error in line 100 (look's like there was unneeded comma... but after correction I've got lots of misunderstanded errors between python versions us google searches said... I am nill in programming, the last wone try was in semi big excell project and now trying to get understandig with that... still nothing😁
> ~/OneShot-GPS-Merge $ python os_gps_merge.py stored.csv Wigle.csv stored_gps.csv
[OneShot] Loaded 431 networks
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/OneShot-GPS-Merge/os_gps_merge.py", line 80, in <module>
    for row in reader:
  File "/data/data/com.termux/files/usr/lib/python3.9/csv.py", line 110, in __next__
    self.fieldnames
  File "/data/data/com.termux/files/usr/lib/python3.9/csv.py", line 97, in fieldnames
    self._fieldnames = next(self.reader)
_csv.Error: line contains NUL

**Comment by eda-abec** [comment]
Hello,
it looks like you are using old Python - like 2.7 or so. You need Python 3, I'll mention it in readme :grin: . Revert to original version (without removed comma etc.) and try running it as
`python3 os_gps_merge.py stored.csv Wigle.csv stored_gps.csv`

or just
`./os_gps_merge.py stored.csv Wigle.csv stored_gps.csv`
after giving it execution right (`chmod +x os_gps_merge.py`)

Let me know if it fixed that :smiley:

**Comment by jevgenyonegin** [comment]
I know about v3
> "/data/data/com.termux/files/usr/lib/**python3.9**/csv.py", line 97, in fieldnames 

 it is used by default in my termux. About syntax error correct, got it when was tryed everything. Anyway, the same result. And the same result on PC.
P.S. omg, I didn't extracted wigle *.csv.gz but simply renamed it😅 Now look's like script working fine, thanks a lot!
P.S.S. Have a nice Christmas and Happy NY🌲
P.P.S. Google mymaps doesn't like output! It want's to be:
> Name,CurrentLatitude,CurrentLongitude 

and same format data:
> Data,Latitude,Longitude

So I simply changed symbols ";" to "," :
> sed  -i 's/;/,/g' stored_gps.csv

and now I can choose every column I want to see, search working fine as well

**Comment by eda-abec** [comment]
Glad to hear you fixed it!

Maybe I could add an option to choose delimiter
I am already thinking of making use of [WiGLE Companion](https://github.com/drygdryg/wigle_companion), which would add the model name and so on. I'm not yet sure how to organize it, whether one script collecting everything and then outputting only required columns, or few small scripts...

Anyway, Merry Christmas and a happy New Year to you and everybody! :snowman_with_snow:

**Comment by eda-abec** [comment]
Delimiter option implemented, closing now.
